import enum
import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, DateTime, Enum, ForeignKey, JSON, String, Text
from sqlalchemy import Uuid as UUID

from app.core.database import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class NotificationSeverity(str, enum.Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class Notification(Base):
    """An alert or notification generated by any module."""

    __tablename__ = "notifications"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    organization_id = Column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    title = Column(String(512), nullable=False)
    message = Column(Text, nullable=False)
    severity = Column(Enum(NotificationSeverity), nullable=False, index=True)

    source_module = Column(String(64), nullable=False, index=True)
    source_id = Column(String(255), nullable=True)

    is_read = Column(Boolean, default=False, nullable=False)
    is_emailed = Column(Boolean, default=False, nullable=False)

    dedup_key = Column(String(512), nullable=True, index=True)

    details = Column(JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), default=utcnow, nullable=False, index=True)

    def __repr__(self) -> str:
        return f"<Notification id={self.id} severity={self.severity}>"
