"""initial schema

Revision ID: d42ba9a73db9
Revises: 
Create Date: 2026-04-04 12:39:24.332853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42ba9a73db9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('domains',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('dns_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ssl_expiry', sa.Date(), nullable=True),
    sa.Column('reputation_score', sa.Integer(), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('dns_records', sa.JSON(), nullable=True),
    sa.Column('scan_findings', sa.JSON(), nullable=True),
    sa.Column('whois_data', sa.JSON(), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_domain'), 'domains', ['domain'], unique=False)
    op.create_index(op.f('ix_domains_organization_id'), 'domains', ['organization_id'], unique=False)
    op.create_table('email_accounts',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('email_address', sa.String(length=512), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_status', sa.String(length=32), nullable=True),
    sa.Column('threats_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_accounts_organization_id'), 'email_accounts', ['organization_id'], unique=False)
    op.create_table('email_threats',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('sender', sa.String(length=512), nullable=False),
    sa.Column('recipient', sa.String(length=512), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('threat_type', sa.String(length=64), nullable=False),
    sa.Column('confidence_score', sa.String(length=16), nullable=True),
    sa.Column('detection_reasons', sa.JSON(), nullable=False),
    sa.Column('spf_result', sa.String(length=16), nullable=True),
    sa.Column('dkim_result', sa.String(length=16), nullable=True),
    sa.Column('dmarc_result', sa.String(length=16), nullable=True),
    sa.Column('suspicious_links', sa.JSON(), nullable=True),
    sa.Column('attachment_hashes', sa.JSON(), nullable=True),
    sa.Column('is_quarantined', sa.Boolean(), nullable=False),
    sa.Column('is_released', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_threats_organization_id'), 'email_threats', ['organization_id'], unique=False)
    op.create_index(op.f('ix_email_threats_severity'), 'email_threats', ['severity'], unique=False)
    op.create_table('monitored_emails',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('email_masked', sa.String(length=255), nullable=False),
    sa.Column('is_breached', sa.Boolean(), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_emails_email_hash'), 'monitored_emails', ['email_hash'], unique=False)
    op.create_index('ix_monitored_emails_org_hash', 'monitored_emails', ['organization_id', 'email_hash'], unique=True)
    op.create_index(op.f('ix_monitored_emails_organization_id'), 'monitored_emails', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('webhook_configs',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_configs_organization_id'), 'webhook_configs', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('breach_records',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('monitored_email_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('breach_name', sa.String(length=255), nullable=False),
    sa.Column('breach_date', sa.Date(), nullable=True),
    sa.Column('data_classes', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitored_email_id'], ['monitored_emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breach_records_monitored_email_id'), 'breach_records', ['monitored_email_id'], unique=False)
    op.create_index(op.f('ix_breach_records_organization_id'), 'breach_records', ['organization_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('user_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='notificationseverity'), nullable=False),
    sa.Column('source_module', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_emailed', sa.Boolean(), nullable=False),
    sa.Column('dedup_key', sa.String(length=512), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_dedup_key'), 'notifications', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_severity'), 'notifications', ['severity'], unique=False)
    op.create_index(op.f('ix_notifications_source_module'), 'notifications', ['source_module'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('sandbox_files',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_magic', sa.String(length=255), nullable=True),
    sa.Column('md5_hash', sa.String(length=32), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'SAFE', 'SUSPICIOUS', 'MALICIOUS', name='filestatus'), nullable=False),
    sa.Column('yara_matches', sa.JSON(), nullable=True),
    sa.Column('virustotal_result', sa.JSON(), nullable=True),
    sa.Column('metadata_extracted', sa.JSON(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_files_md5_hash'), 'sandbox_files', ['md5_hash'], unique=False)
    op.create_index(op.f('ix_sandbox_files_organization_id'), 'sandbox_files', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sandbox_files_sha256_hash'), 'sandbox_files', ['sha256_hash'], unique=False)
    op.create_table('web_scans',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('domain_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'MANUAL', name='scanfrequency'), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_scans_domain_id'), 'web_scans', ['domain_id'], unique=False)
    op.create_index('ix_web_scans_org_domain', 'web_scans', ['organization_id', 'domain_id'], unique=False)
    op.create_index(op.f('ix_web_scans_organization_id'), 'web_scans', ['organization_id'], unique=False)
    op.create_table('scan_findings',
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('scan_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cve_id', sa.String(length=32), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['web_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_findings_organization_id'), 'scan_findings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scan_findings_scan_id'), 'scan_findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scan_findings_severity'), 'scan_findings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_findings_severity'), table_name='scan_findings')
    op.drop_index(op.f('ix_scan_findings_scan_id'), table_name='scan_findings')
    op.drop_index(op.f('ix_scan_findings_organization_id'), table_name='scan_findings')
    op.drop_table('scan_findings')
    op.drop_index(op.f('ix_web_scans_organization_id'), table_name='web_scans')
    op.drop_index('ix_web_scans_org_domain', table_name='web_scans')
    op.drop_index(op.f('ix_web_scans_domain_id'), table_name='web_scans')
    op.drop_table('web_scans')
    op.drop_index(op.f('ix_sandbox_files_sha256_hash'), table_name='sandbox_files')
    op.drop_index(op.f('ix_sandbox_files_organization_id'), table_name='sandbox_files')
    op.drop_index(op.f('ix_sandbox_files_md5_hash'), table_name='sandbox_files')
    op.drop_table('sandbox_files')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_source_module'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_severity'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_dedup_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_breach_records_organization_id'), table_name='breach_records')
    op.drop_index(op.f('ix_breach_records_monitored_email_id'), table_name='breach_records')
    op.drop_table('breach_records')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_webhook_configs_organization_id'), table_name='webhook_configs')
    op.drop_table('webhook_configs')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_monitored_emails_organization_id'), table_name='monitored_emails')
    op.drop_index('ix_monitored_emails_org_hash', table_name='monitored_emails')
    op.drop_index(op.f('ix_monitored_emails_email_hash'), table_name='monitored_emails')
    op.drop_table('monitored_emails')
    op.drop_index(op.f('ix_email_threats_severity'), table_name='email_threats')
    op.drop_index(op.f('ix_email_threats_organization_id'), table_name='email_threats')
    op.drop_table('email_threats')
    op.drop_index(op.f('ix_email_accounts_organization_id'), table_name='email_accounts')
    op.drop_table('email_accounts')
    op.drop_index(op.f('ix_domains_organization_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_domain'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
